spring:
  r2dbc:
    mappings:
      naming-strategy: SNAKE_CASE
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: root
  flyway:
    locations: classpath:db/migration
